version: '3.8'

services:
  fastapi:
    build:
      context: ./src/python
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/python:/app
    depends_on:
      - db

  nuxt:
    build:
      context: ./src/js
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - fastapi

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
